#
#  Copyright (c) 2012-2019 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
name: Docker
#on: [pull_request, push]
on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build image on amd
      run: docker build .
    - name: Build on s390x
      uses: uraimo/run-on-arch-action@master
      id: runcmd
      with:
        architecture: s390x
        distribution: ubuntu18.04
        run: |
          docker build .
